FROM node:13.12.0-alpine

# set working directory
WORKDIR /frontend 

# add `/app/node_modules/.bin` to $PATH
ENV PATH /frontend/node_modules/.bin:$PATH

# install app dependencies
COPY frontend/package.json .
COPY frontend/package-lock.json .
RUN npm install --silent
RUN npm install react-scripts@5.0.1 -g --silent
RUN npm install bootstrap@5.1 react-bootstrap --save

# add app
COPY frontend/ .

# start app
CMD ["npm", "start"]